services:
  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_DB: kubsu
      POSTGRES_USER: kubsu
      POSTGRES_PASSWORD: kubsu
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8016:8016"
    depends_on:
      - db
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+psycopg://kubsu:kubsu@db:5432/kubsu
