version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: kubsu
      POSTGRES_USER: kubsu
      POSTGRES_PASSWORD: kubsu
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kubsu -d kubsu"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8016:8016"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+psycopg://kubsu:kubsu@db:5432/kubsu"
    restart: unless-stopped