name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/your-image-name:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/your-image-name:latest

  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Pull and run tests
      run: |
        docker pull ghcr.io/${{ github.repository_owner }}/your-image-name:latest
        docker run --rm ghcr.io/${{ github.repository_owner }}/your-image-name:latest pytest

  deploy:
    needs: [build, test]
    runs-on: self-hosted
    steps:
      - name: Deploy via Podman
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            podman pull ghcr.io/${{ github.repository_owner }}/your-image-name:latest
            podman stop your-container-name || true
            podman rm your-container-name || true
            podman run -d --name your-container-name -p 8016:8016 ghcr.io/${{ github.repository_owner }}/your-image-name:latest
  
