name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker-compose build

  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build and Run Tests
      run: |
        docker-compose build
        docker-compose up --abort-on-container-exit --exit-code-from test test

  deploy:
    needs: [build, test]
    runs-on: self-hosted
  
    steps:
      - name: Deploy via Podman
        uses: appleboy/ssh-action@v0.1.5
        with:
          debug: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -eux
            cd /home/${{ secrets.USER }}/tasks/docker
            podman-compose down -v
            podman-compose build
            podman-compose up -d
