name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Add all repository
        uses: actions/checkout@v3

      - name: Build all images
        run: docker-compose build
      
      - name: Check existence images
        run: |
          docker image inspect postgres:15-alpine

  test:
    name: Testing
    runs-on: self-hosted
    needs: build
    env:
      DB_USER: kubsu
      DB_PASSWORD: kubsu
      DB_NAME: kubsu
    steps:
      - uses: actions/checkout@v3
      
      - name: Build test image
        run: docker-compose build test
      
      - name: Start dependencies
        run: docker-compose up -d db 
      
      - name: Wait for Postgres
        run: |
          for i in {1..5}; do
            docker-compose exec -T db pg_isready -U kubsu && break
            echo "Waiting for Postgres: ($i/5)"
            sleep 10
          done
      
      - name: Run tests
        run: docker-compose run --rm test
      
      - name: Cleanup
        run: docker-compose down -v
      
      - name: Clean working directory
        run: rm -rf $GITHUB_WORKSPACE/* 

  deploy:
    needs: [build, test]
    runs-on: self-hosted
    
    steps:
    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.USER }}/tasks/docker
          docker-compose -f docker-compose.prod.yml pull
          docker-compose -f docker-compose.prod.yml down
          docker-compose -f docker-compose.prod.yml up -d
