name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker-compose build

  test:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Start services
      run: docker-compose up -d
    - name: Run tests inside container
      run: docker exec $(docker ps -q -f name=web) pytest --disable-warnings
    - name: Cleanup after tests
      run: docker-compose down

  deploy:
    runs-on: self-hosted
    needs: test

    steps:
    - uses: actions/checkout@v4
    - name: Deploy application
      run: |
        docker-compose down
        docker-compose up -d
